%%% Cleaning the workspace and history command %%%
clear;
clc;

%%% X and Y coordinates for the bubbles' centers %%%
bubblesCenterYCoordinates = [340 367 394 421 448 475 502 529 556 583 ...
    610 637 664 691 718 745 772 799 826 853];
bubblesCenterXCoordinates = [116 145 174 203 232 355 384 413 442 471 ...
    593 622 651 680 709];

%%% Amout of Columns in the exam %%%
columnsAmout = 3;
%%% Amout of Questions Options per question %%%%
questionsItemsAmout = 5;

%%%  Computing the corresponding (x, y) coordinate for each bubble %%%
bubblesCenterCoordinates = computeBubblesCenters( ...
    bubblesCenterXCoordinates, bubblesCenterYCoordinates, columnsAmout);

%%% Computing the set of answers belong to each question %%%
answersForQuestions = computeAnswersBubbles('only_logos_template.png', ...
    'a_referring_exam.png', bubblesCenterCoordinates, 100, 10, ...
    questionsItemsAmout);

%%% Displaying the result of processing the image %%%
for questionsCounter = 1:size(answersForQuestions, 2)
    % Question #NUMBER -> [0/1 0/1 0/1 0/1 0/1]
    fprintf(1, '%s%d -> [%d %d %d %d %d]\n', 'Question #', ...
        answersForQuestions(questionsCounter).id, ...
        answersForQuestions(questionsCounter).items(1), ...
        answersForQuestions(questionsCounter).items(2), ...
        answersForQuestions(questionsCounter).items(3), ...
        answersForQuestions(questionsCounter).items(4), ...
        answersForQuestions(questionsCounter).items(5));
end